#!/usr/bin/env python3
# [METADATA]
# TOOL_NAME = rsem
# VERSION = 1.3.3
# THREADS = 1
# PROFILE = calculate_expression_quanti

"""
Tool: rsem (1.3.3)
Profile: calculate_expression_quanti
"""
import argparse
import os
import subprocess

def main():
    parser = argparse.ArgumentParser(description="rsem Analysis Runner")
    
    # --- [Argument Parsing] ---
    parser.add_argument('--SeqID', required=True, default='', help='Unique sample identifier used for naming the output files (e.g., .genes.results). (Default: )')
    parser.add_argument('--TranscriptomeBam', required=True, default='', help='Path to the BAM file aligned to the transcriptome. Required: STAR\'s Aligned.toTranscriptome.out.bam. (Default: )')
    parser.add_argument('--InputSuffix', required=False, default='.Aligned.toTranscriptome.out.bam', help='Suffix for the input BAM file if not using the default STAR transcriptome BAM (Default: .Aligned.toTranscriptome.out.bam)')
    parser.add_argument('--RsemIndex', required=True, default='', help='The prefix of the RSEM reference index (generated by rsem-prepare-reference). (Default: )')
    parser.add_argument('--OutputDir', required=True, default='', help='Directory where the quantification results and diagnostic logs will be stored. (Default: )')
    parser.add_argument('--Threads', required=False, default='12', help='Number of threads to use for the calculation. (Default: 12)')
    parser.add_argument('--PairedFlag', required=False, default='--paired-end', help='Explicit flag for paired-end data. Must provide \'--paired-end\' for PE or \'\' for SE. (Default: --paired-end)')
    parser.add_argument('--NoBamOutput', required=False, default='--no-bam-output', help='If true, applies \'--no-bam-output\' to suppress BAM file generation (saves disk space). (Default: --no-bam-output)')
    parser.add_argument('--EstimateRspd', required=False, default='--estimate-rspd', help='If true, applies \'--estimate-rspd\' to estimate the read start position distribution. (Default: --estimate-rspd)')
    parser.add_argument('--StrandOption', required=False, default='none', help='Strandedness configuration. Must provide one of: \'none\', \'forward\', or \'reverse\'. (Default: none)')
    parser.add_argument('--ExtraArgs', required=False, default='None', help='Additional RSEM parameters (e.g., \'--estimate-rspd --no-bam-output\'). Pass \'\' if not needed. (Default: None)')
    parser.add_argument('--singularity_bin', required=False, default='singularity', help='Absolute path to the singularity/apptainer executable. (Default: singularity)')
    parser.add_argument('--rsem_sif', required=False, default='/storage/images/rsem-1.3.3.sif', help='Path to the RSEM singularity image file (.sif). (Default: /storage/images/rsem-1.3.3.sif)')
    parser.add_argument('--bind', required=False, default='/storage,/data', help='Host paths to mount inside the container (e.g., \'/storage,/data\'). (Default: /storage,/data)')
    
    args = parser.parse_args()

    # --- [Variable Declarations: Key = Value] ---
    SeqID = args.SeqID
    TranscriptomeBam = args.TranscriptomeBam
    InputSuffix = args.InputSuffix
    RsemIndex = args.RsemIndex
    OutputDir = args.OutputDir
    Threads = args.Threads
    PairedFlag = args.PairedFlag
    NoBamOutput = args.NoBamOutput
    EstimateRspd = args.EstimateRspd
    StrandOption = args.StrandOption
    ExtraArgs = args.ExtraArgs
    singularity_bin = args.singularity_bin
    rsem_sif = args.rsem_sif
    bind = args.bind

    # --- [Output Paths] ---

    # --- [Command Execution] ---
    cmd = f"{singularity_bin} exec -B {bind} {rsem_sif} rsem-calculate-expression {PairedFlag} {NoBamOutput} {EstimateRspd} {ExtraArgs} --num-threads {Threads} --strandedness {StrandOption} --alignments {TranscriptomeBam}/{SeqID}{InputSuffix} {RsemIndex} {OutputDir}/{SeqID}"
    
    print(f"\\n[RUNNING]\\n{cmd}\\n")
    
    os.makedirs(os.path.dirname(OutputDir) if '.' in os.path.basename(OutputDir) else OutputDir, exist_ok=True)
    
    subprocess.run(cmd, shell=True, check=True)

if __name__ == "__main__":
    main()