#!/bin/bash
# [METADATA]
# TOOL_NAME = rsem
# VERSION = 1.3.3
# THREADS = 1

# Tool Info: rsem (1.3.3)
# Profile: calculate_expression_quanti

usage() {
    echo "Usage: $0 [options]"
    echo ""
    echo "Required Inputs:"
    echo "  --SeqID           Unique sample identifier used for naming the output files (e.g., .genes.results)."
    echo "  --TranscriptomeBam Path to the BAM file aligned to the transcriptome. Required: STAR's Aligned.toTranscriptome.out.bam."
    echo "  --RsemIndex       The prefix of the RSEM reference index (generated by rsem-prepare-reference)."
    echo "  --OutputDir       Directory where the quantification results and diagnostic logs will be stored."
    echo ""
    echo "Optional Parameters:"
    echo "  --InputSuffix     Suffix for the input BAM file if not using the default STAR transcriptome BAM (Default: .Aligned.toTranscriptome.out.bam)"
    echo "  --Threads         Number of threads to use for the calculation. (Default: 12)"
    echo "  --PairedFlag      Explicit flag for paired-end data. Must provide '--paired-end' for PE or '' for SE. (Default: --paired-end)"
    echo "  --NoBamOutput     If true, applies '--no-bam-output' to suppress BAM file generation (saves disk space). (Default: --no-bam-output)"
    echo "  --EstimateRspd    If true, applies '--estimate-rspd' to estimate the read start position distribution. (Default: --estimate-rspd)"
    echo "  --StrandOption    Strandedness configuration. Must provide one of: 'none', 'forward', or 'reverse'. (Default: none)"
    echo "  --ExtraArgs       Additional RSEM parameters (e.g., '--estimate-rspd --no-bam-output'). Pass '' if not needed. (Default: None)"
    echo "  --singularity_bin Absolute path to the singularity/apptainer executable. (Default: singularity)"
    echo "  --rsem_sif        Path to the RSEM singularity image file (.sif). (Default: /storage/images/rsem-1.3.3.sif)"
    echo "  --bind            Host paths to mount inside the container (e.g., '/storage,/data'). (Default: /storage,/data)"
    echo "  -h, --help       Show this help message"
    exit 1
}

# --- [Default Variable Declarations] ---
# YAML의 기본값들이 이곳에 Key="Value" 형태로 정의됩니다.
SeqID=""
TranscriptomeBam=""
InputSuffix=".Aligned.toTranscriptome.out.bam"
RsemIndex=""
OutputDir=""
Threads="12"
PairedFlag="--paired-end"
NoBamOutput="--no-bam-output"
EstimateRspd="--estimate-rspd"
StrandOption="none"
ExtraArgs="None"
singularity_bin="singularity"
rsem_sif="/storage/images/rsem-1.3.3.sif"
bind="/storage,/data"

# --- [Argument Parsing] ---
while [[ $# -gt 0 ]]; do
    case "$1" in
        --SeqID) SeqID="$2"; shift 2 ;;
        --TranscriptomeBam) TranscriptomeBam="$2"; shift 2 ;;
        --InputSuffix) InputSuffix="$2"; shift 2 ;;
        --RsemIndex) RsemIndex="$2"; shift 2 ;;
        --OutputDir) OutputDir="$2"; shift 2 ;;
        --Threads) Threads="$2"; shift 2 ;;
        --PairedFlag) PairedFlag="$2"; shift 2 ;;
        --NoBamOutput) NoBamOutput="$2"; shift 2 ;;
        --EstimateRspd) EstimateRspd="$2"; shift 2 ;;
        --StrandOption) StrandOption="$2"; shift 2 ;;
        --ExtraArgs) ExtraArgs="$2"; shift 2 ;;
        --singularity_bin) singularity_bin="$2"; shift 2 ;;
        --rsem_sif) rsem_sif="$2"; shift 2 ;;
        --bind) bind="$2"; shift 2 ;;
        -h|--help) usage ;;
        *) echo "Unknown argument: $1"; usage ;;
    esac
done

# --- [Validation] ---
# 필수 입력값(required: true)이 비어있는지 체크합니다.
if [[ -z "${SeqID:-}" ]]; then echo "Error: --SeqID is required"; usage; fi
if [[ -z "${TranscriptomeBam:-}" ]]; then echo "Error: --TranscriptomeBam is required"; usage; fi
if [[ -z "${RsemIndex:-}" ]]; then echo "Error: --RsemIndex is required"; usage; fi
if [[ -z "${OutputDir:-}" ]]; then echo "Error: --OutputDir is required"; usage; fi

# --- [Output Paths] ---

# --- [Command Execution] ---
# [Key]가 $Key 형태로 치환된 최종 커맨드입니다.
cmd="${singularity_bin} exec -B ${bind} ${rsem_sif} rsem-calculate-expression ${PairedFlag} ${NoBamOutput} ${EstimateRspd} ${ExtraArgs} --num-threads ${Threads} --strandedness ${StrandOption} --alignments ${TranscriptomeBam}/${SeqID}${InputSuffix} ${RsemIndex} ${OutputDir}/${SeqID}"

echo -e "\\n[RUNNING]\\n$cmd\\n"

# 자동 디렉토리 생성
mkdir -p "$(dirname "${OutputDir}")" 2>/dev/null || mkdir -p "${OutputDir}"

eval "$cmd"